[versions]
androidDesugarJdkLibs = "2.1.5"
# AGP and tools should be updated together
androidGradlePlugin = "8.10.1"
androidTools = "31.10.0"
androidxActivity = "1.10.1"
fragment = "1.8.8"
androidxAppCompat = "1.7.1"
androidxBrowser = "1.8.0"
androidxCore = "1.16.0"
androidxCoreSplashscreen = "1.0.1"
androidxConstraintlayout = "1.0.1"
androidxLifecycle = "2.9.6"
coil = "3.3.0"
# @keep
compileSdk = "36"
junit = "4.13.2"
kotlin = "2.1.20"
kotlinxCoroutines = "1.10.1"
kotlinxSerializationJson = "1.8.0"
ksp = "2.1.20-2.0.0"
mammoth = "1.5.0" #1.7.0依赖问题导致崩溃,1.8.0不崩溃但无法解析,1.5.0有些docx转换失败
minSdk = "23"
mmkv = "2.2.3"
mupdfFitz = "1.26.5"
okhttp = "4.12.0"
crashreport = "4.1.9.3"
room = "2.8.0"

constraintLayout = "2.2.1"
umengCommon = "9.6.5"
umengAsms = "1.8.0"
colorPickerDialog = "0.2.2"
flinger = "1.1.1"
paging = "3.3.2"
tiff-android = "1.1.2"
penfeizhou = "3.0.5"
android-gif-drawable = "1.2.29"

# @keep
targetSdk = "35"
version-catalog-update = "0.8.0"
material = "1.13.0"
material3 = "1.1.2"
material3Android = "1.3.1"
multidex = "2.0.1"
viewpager2 = "1.2.0"
vectordrawable = "1.2.0"
swiperefreshlayout = "1.2.0-beta01"
recyclerview = "1.4.0"
sardine = "0.9"
k2pdfopt = "0.2.0"
juniversalchardet = "2.5.0"

versionCode = "480"
versionName = "7.8.0"

[libraries]
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }

androidx-fragment = { group = "androidx.fragment", name = "fragment", version.ref = "fragment" }

androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-lifecycle-runtimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodelKtx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-livedata = { group = "androidx.lifecycle", name = "lifecycle-livedata", version.ref = "androidxLifecycle" }

coil-kt = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-kt-network-okhttp = { group = "io.coil-kt.coil3-network-okhttp", name = "coil", version.ref = "coil" }

kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

mammoth = { module = "org.zwobble.mammoth:mammoth", version.ref = "mammoth" }
mupdf-fitz = { module = "com.artifex.mupdf:mupdf-fitz", version.ref = "mupdfFitz" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }

umeng-asms = { module = "com.umeng.umsdk:asms", version.ref = "umengAsms" }
umeng-common = { module = "com.umeng.umsdk:common", version.ref = "umengCommon" }
colorPickerDialog = { module = "me.jfenn.ColorPickerDialog:base", version.ref = "colorPickerDialog" }
flinger = { module = "com.github.iamjosephmj:flinger", version.ref = "flinger" }

multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
vectordrawable = { group = "androidx.vectordrawable", name = "vectordrawable", version.ref = "vectordrawable" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
sardine = { group = "com.github.thegrizzlylabs", name = "sardine-android", version.ref = "sardine" }
k2pdfopt = { group = "com.archko.reader", name = "k2pdfopt", version.ref = "k2pdfopt" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
crashreport = { module = "com.tencent.bugly:crashreport", version.ref = "crashreport" }
juniversalchardet = { module = "com.github.albfernandez:juniversalchardet", version.ref = "juniversalchardet" }

penfeizhou-awebp = { group = "com.github.penfeizhou.android.animation", name = "awebp", version.ref = "penfeizhou" }
android-gif-drawable = { module = "pl.droidsonroids.gif:android-gif-drawable", version.ref = "android-gif-drawable" }
tiff-loader = { module = "com.archko.reader.image:library-android", version.ref = "tiff-android" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
